version: "3.7"

services:
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "15592:1433"
    environment:
      SA_PASSWORD: "Password0!"
      ACCEPT_EULA: "Y"
  api:
    container_name: api
    build:
      context: ./store.api
      dockerfile: Dockerfile
    ports:
      - "5000:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_GENERATE_ASPNET_CERTIFICATE=true
      - DOTNET_RUNNING_IN_CONTAINER=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
      - NUGET_PACKAGES=/root/.nuget/fallbackpackages
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ./store.api/store.api/.:/src/store.api
      - ./store.api/store.dal/.:/src/store.dal
      - ./store.api/store.models/.:/src/store.models
  web:
    container_name: web
    build:
      context: ./store.web
      dockerfile: Dockerfile
    ports:
      - "8000:4200"
    volumes:
      - ./store.web/.:/app
