// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace store.dal.Models
{
    /// <summary>
    /// The Update Log will capture UIC records processed for a downloaddate.
    /// </summary>
    public partial class AtbUpdateLog
    {
        /// <summary>
        /// Unique Log Identifier
        /// </summary>
        public int LogId { get; set; }
        public DateTime? DownLoadDate { get; set; }
        /// <summary>
        /// Database where the update occurred
        /// </summary>
        public string DatabaseName { get; set; }
        public string ProcessName { get; set; }
        /// <summary>
        /// Schema where Update occurred
        /// </summary>
        public string SchemaName { get; set; }
        /// <summary>
        /// TableName Updated
        /// </summary>
        public string TableName { get; set; }
        /// <summary>
        /// Column Updated
        /// </summary>
        public string ColumnName { get; set; }
        /// <summary>
        /// Number of Rows Updated
        /// </summary>
        public int RowCount { get; set; }
        /// <summary>
        /// Description of the Update
        /// </summary>
        public string UpdateLogDescription { get; set; }
        /// <summary>
        /// User Name of Update
        /// </summary>
        public string UpdateUser { get; set; }
        /// <summary>
        /// Update Initiative Name
        /// </summary>
        public string UpdateInitiative { get; set; }
        /// <summary>
        /// Source of Update
        /// </summary>
        public string Source { get; set; }
        /// <summary>
        /// Date of Update
        /// </summary>
        public DateTime UpdateDate { get; set; }
    }
}