// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace store.dal.Models
{
    /// <summary>
    /// This table contains country codes based on the Geopolitical Entities, Names, and Codes (GENC) Standard. The Geopolitical Entities, Names, and Codes (GENC) Standard is the U.S. Government profile of ISO 3166 Codes for the representation of names of countries and their subdivisions. It specifies an authoritative set of country codes and names for use by the Federal Government for information exchange, using ISO 3166 (Parts 1 and 2) names and code elements wherever possible, with modifications only where necessary to comply with U.S. law and U.S. Government recognition policy. Entries of the GENC Standard are either based on direct reuse of ISO 3166 code elements, or are a type of variation from that standard (Exclusion, Exception, Extension, or Exigent) based on U.S. government requirements. Note that in the case of Exceptions, the codes do not differ from ISO 3166. Exceptions are based on differences in naming (some politically significant, others simply stylistic) as approved by the United States Board on Geographic Names, and/or differences in how the territorial extent of an entity is understood. GENC Extensions introduce new codes not included in ISO 3166. Entries from ISO 3166 that are excluded from the GENC Standard may be browsed in the GENC Entries Register.  External Data Source.
    /// </summary>
    public partial class LtbCountry
    {
        public LtbCountry()
        {
            InverseCountryParent = new HashSet<LtbCountry>();
            LtbAirports = new HashSet<LtbAirport>();
            LtbCounties = new HashSet<LtbCounty>();
            LtbCountryWorldRegionAssociations = new HashSet<LtbCountryWorldRegionAssociation>();
            LtbDoDdmismedicalTreatmentFacilities = new HashSet<LtbDoDdmismedicalTreatmentFacility>();
            LtbDoDinstallationMdes = new HashSet<LtbDoDinstallationMde>();
            LtbDoDinstallations = new HashSet<LtbDoDinstallation>();
            LtbDoDrealPropertyAssets = new HashSet<LtbDoDrealPropertyAsset>();
            LtbDoDuccommandAreaOfResponsibilities = new HashSet<LtbDoDuccommandAreaOfResponsibility>();
            LtbGeographicLocations = new HashSet<LtbGeographicLocation>();
            LtbManufacturers = new HashSet<LtbManufacturer>();
            LtbOshaEstablishments = new HashSet<LtbOshaEstablishment>();
            LtbStations = new HashSet<LtbStation>();
            LtbZipCodes = new HashSet<LtbZipCode>();
        }

        /// <summary>
        /// Unique generated number for the record used for row identity.
        /// </summary>
        public int CountryId { get; set; }
        /// <summary>
        /// A code value for the current record.
        /// </summary>
        public string CountryCode3Char { get; set; }
        /// <summary>
        /// A code value for the current record.
        /// </summary>
        public string CountryCode2Char { get; set; }
        /// <summary>
        /// NumericCode value for the DMIS Medical Treatment Facility.
        /// </summary>
        public string NumericCode { get; set; }
        /// <summary>
        /// A brief representation or account of the current value represented by the associated record.
        /// </summary>
        public string ShortDescription { get; set; }
        /// <summary>
        /// A detailed representation of the current value represented by the associated record.
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// Unique Identifier indicating U.S. relationship.
        /// </summary>
        public int CountryUsrecognitionId { get; set; }
        /// <summary>
        /// Unique Identifier indicating Status of Country relation bewteen GENC Standards and ISO 3166 standard.
        /// </summary>
        public int CountryGencstatusId { get; set; }
        /// <summary>
        /// Record Parent ID with Foreign key to the Primary key of the table.
        /// </summary>
        public int? CountryParentId { get; set; }
        /// <summary>
        /// The definition of the code value according to Regulatory Guidance or Business.
        /// </summary>
        public string ValueDefinition { get; set; }
        /// <summary>
        /// The Business Rule, Regulatory or Other Army/DoD Guidance that states the code use requirement.  If available, include the publish and effective dates.
        /// </summary>
        public string Guidance { get; set; }
        /// <summary>
        /// The date the code value was established for use.  This date may or may not be the same as the start collecting date.
        /// </summary>
        public DateTime? EstablishDate { get; set; }
        /// <summary>
        /// Date the code value was available to be assigned to a record.  Records assigned the code value must have a Date greater than or equal to the Start Collecting Date. Will default to the current date upon entry unless otherwise specified.  The time for start collecting date should always be 0000.
        /// </summary>
        public DateTime StartCollecting { get; set; }
        /// <summary>
        /// Date the code was taken out of circulation for collection.  Incidents assigned the code value must have a Date Occurred less than or equal to the End Collecting Date.  The time for end collecting date should always be 2359.
        /// </summary>
        public DateTime? EndCollecting { get; set; }
        /// <summary>
        /// A flag to indicate whether the code is active and assigned to action records. If no records have the code assigned and it is no longer active,  then the current value should be N. Valid values: Y/N
        /// </summary>
        public string Used { get; set; }
        /// <summary>
        /// Numeric sorting order to control the way the codes/types are listed in drop downs within the application or module.
        /// </summary>
        public int? DisplayOrder { get; set; }
        /// <summary>
        /// The user who created the record.
        /// </summary>
        public string CreatedByUser { get; set; }
        /// <summary>
        /// The date the record was created.
        /// </summary>
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// Application used to create the record.
        /// </summary>
        public string CreatedByApp { get; set; }
        /// <summary>
        /// The user to last update the record.
        /// </summary>
        public string LastModifiedByUser { get; set; }
        /// <summary>
        /// The date the record was last updated.
        /// </summary>
        public DateTime LastModifiedDate { get; set; }
        /// <summary>
        /// Application used to last update the record.
        /// </summary>
        public string LastModifiedByApp { get; set; }

        public virtual LtbCountryGencstatus CountryGencstatus { get; set; }
        public virtual LtbCountry CountryParent { get; set; }
        public virtual LtbCountryUsrecognition CountryUsrecognition { get; set; }
        public virtual ICollection<LtbCountry> InverseCountryParent { get; set; }
        public virtual ICollection<LtbAirport> LtbAirports { get; set; }
        public virtual ICollection<LtbCounty> LtbCounties { get; set; }
        public virtual ICollection<LtbCountryWorldRegionAssociation> LtbCountryWorldRegionAssociations { get; set; }
        public virtual ICollection<LtbDoDdmismedicalTreatmentFacility> LtbDoDdmismedicalTreatmentFacilities { get; set; }
        public virtual ICollection<LtbDoDinstallationMde> LtbDoDinstallationMdes { get; set; }
        public virtual ICollection<LtbDoDinstallation> LtbDoDinstallations { get; set; }
        public virtual ICollection<LtbDoDrealPropertyAsset> LtbDoDrealPropertyAssets { get; set; }
        public virtual ICollection<LtbDoDuccommandAreaOfResponsibility> LtbDoDuccommandAreaOfResponsibilities { get; set; }
        public virtual ICollection<LtbGeographicLocation> LtbGeographicLocations { get; set; }
        public virtual ICollection<LtbManufacturer> LtbManufacturers { get; set; }
        public virtual ICollection<LtbOshaEstablishment> LtbOshaEstablishments { get; set; }
        public virtual ICollection<LtbStation> LtbStations { get; set; }
        public virtual ICollection<LtbZipCode> LtbZipCodes { get; set; }
    }
}