// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace store.dal.Models
{
    /// <summary>
    /// This table contains the Raw Personnel data from DMDC.   External Data Source.
    /// </summary>
    public partial class LtbDmdcpersonnelListing
    {
        /// <summary>
        /// Unique generated number for the record used for row identity.
        /// </summary>
        public int DmdcpersonnelListingId { get; set; }
        /// <summary>
        /// The EDIPI of the DMDC Personnel.
        /// </summary>
        public string Edipi { get; set; }
        /// <summary>
        /// The SSN of the DMDC personnel.
        /// </summary>
        public string Ssn { get; set; }
        /// <summary>
        /// DMDC personnel Last name.
        /// </summary>
        public string LastName { get; set; }
        /// <summary>
        /// DMDC personnel first name.
        /// </summary>
        public string FirstName { get; set; }
        /// <summary>
        /// The middle name of the DMDC personnel.
        /// </summary>
        public string MiddleName { get; set; }
        /// <summary>
        /// The cadency of the DMDC personnel.
        /// </summary>
        public string Cadency { get; set; }
        /// <summary>
        /// DMDC personnel birth date.
        /// </summary>
        public string BirthDate { get; set; }
        public string EmailId { get; set; }
        /// <summary>
        /// DMD Personnel Age value.
        /// </summary>
        public int? Age { get; set; }
        /// <summary>
        /// Unique Id respresenting the DMDC personnel gender.
        /// </summary>
        public int? GenderId { get; set; }
        /// <summary>
        /// Unique ID representing Department of Defense (DoD) Service.
        /// </summary>
        public int? DoDserviceId { get; set; }
        /// <summary>
        /// A code value for the current record.
        /// </summary>
        public string UniformedServiceOrganizationComponentCode { get; set; }
        /// <summary>
        /// Unique ID representing the pay grade of DMDC personnel.
        /// </summary>
        public int? PayGradeId { get; set; }
        /// <summary>
        /// A code value for the current record.
        /// </summary>
        public string PayGradeModifierCode { get; set; }
        /// <summary>
        /// A code value for the current record.
        /// </summary>
        public string UscitizenStatusCode { get; set; }
        /// <summary>
        /// Unique ID representing the primary MOS/Civilian job series of the DMDC personnel.
        /// </summary>
        public int? PrimaryMoscivJobSeriesJobTitleId { get; set; }
        /// <summary>
        /// Unique ID representing the DMDC personnel duty MOS/Civilian Job Series.
        /// </summary>
        public int? DutyMoscivJobSeriesJobTitleId { get; set; }
        /// <summary>
        /// Unique ID representing the secondary MOS/Civilian job series of the DMDC personnel.
        /// </summary>
        public int? SecondaryMoscivJobSeriesJobTitleId { get; set; }
        /// <summary>
        /// Unique ID representing the primary DoD occupational code of the DMDC personnel.
        /// </summary>
        public int? PrimaryDoDoccupationalJobTitleId { get; set; }
        /// <summary>
        /// Unique ID representing the Duty DoD occupational job title of the DMDC personnel.
        /// </summary>
        public int? DutyDoDoccupationalJobTitleId { get; set; }
        /// <summary>
        /// Unique ID representing the secondary DoD occupational code of the DMDC personnel.
        /// </summary>
        public int? SecondaryDoDoccupationalJobTitleId { get; set; }
        /// <summary>
        /// A code value for the current record.
        /// </summary>
        public string MilAeronauticalRatingCode { get; set; }
        /// <summary>
        /// A code value for the current record.
        /// </summary>
        public string MilFlyingStatusIndicatorCode { get; set; }
        /// <summary>
        /// Unique ID representing the Personnel Assigned UIC.
        /// </summary>
        public int? AssignedUicid { get; set; }
        /// <summary>
        /// Unique ID representing the DMDC personnel assigned location state.
        /// </summary>
        public int? AssignedLocationStateId { get; set; }
        /// <summary>
        /// Unique ID representing the DMDC personnel assigned location country.
        /// </summary>
        public int? AssignedLocationCountryId { get; set; }
        /// <summary>
        /// A code value for the current record.
        /// </summary>
        public string AssignedLocationZipCode5Digit { get; set; }
        /// <summary>
        /// A code value for the current record.
        /// </summary>
        public string AssignedLocationZipCode4Digit { get; set; }
        /// <summary>
        /// Code representing the DMDC personnel assigned country.
        /// </summary>
        public string AssignedLocationCountyCode { get; set; }
        /// <summary>
        /// A code value for the current record.
        /// </summary>
        public string AssignedMajorCommandCode { get; set; }
        /// <summary>
        /// Unique ID representing the DMDC personnel assigned location DoD Installation.
        /// </summary>
        public int? AssignedDoDinstallationId { get; set; }
        /// <summary>
        /// Unique ID representing the duty UIC of the DMDC personnel.
        /// </summary>
        public int? DutyUicid { get; set; }
        /// <summary>
        /// Unique ID representing the Duty State of the DMDC personnel.
        /// </summary>
        public int? DutyLocationStateId { get; set; }
        /// <summary>
        /// Unique ID representing the Duty country location of the DMDC personnel.
        /// </summary>
        public int? DutyLocationCountryId { get; set; }
        /// <summary>
        /// A code value for the current record.
        /// </summary>
        public string DutyLocationZipCode5Digit { get; set; }
        /// <summary>
        /// A code value for the current record.
        /// </summary>
        public string DutyLocationZipCode4Digit { get; set; }
        /// <summary>
        /// A code value for the current record.
        /// </summary>
        public string DutyLocationCountyCode { get; set; }
        /// <summary>
        /// A code value for the current record.
        /// </summary>
        public string DutyMajorCommandCode { get; set; }
        /// <summary>
        /// Unique ID representing the Duty DoD Installation of the DMDC personnel.
        /// </summary>
        public int? DutyDoDinstallationId { get; set; }
        /// <summary>
        /// The start date of the DMDC personnel record.
        /// </summary>
        public string StartDate { get; set; }
        /// <summary>
        /// The response received from DMDC.
        /// </summary>
        public string Dmdcresponse { get; set; }
        /// <summary>
        /// The Unique Identifier for the DMDC personnel.
        /// </summary>
        public Guid OrigUniqueIdentifier { get; set; }
        /// <summary>
        /// DMDC record last updated date.
        /// </summary>
        public DateTime? LastUpdated { get; set; }
        /// <summary>
        /// The user who created the record.
        /// </summary>
        public string CreatedByUser { get; set; }
        /// <summary>
        /// The date the record was created.
        /// </summary>
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// Application used to create the record.
        /// </summary>
        public string CreatedByApp { get; set; }
        /// <summary>
        /// The user to last update the record.
        /// </summary>
        public string LastModifiedByUser { get; set; }
        /// <summary>
        /// The date the record was last updated.
        /// </summary>
        public DateTime LastModifiedDate { get; set; }
        /// <summary>
        /// Application used to last update the record.
        /// </summary>
        public string LastModifiedByApp { get; set; }
    }
}