// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace store.dal.Models
{
    public partial class LtbPrmdocumentType
    {
        public string Code { get; set; }
        public string Description { get; set; }
    }
}