// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace store.dal.Models
{
    /// <summary>
    /// This table contains a list of DoD Medical Facility Types  provide by DMIS.  External Data Source.
    /// </summary>
    public partial class LtbTcdoDmedicalFacilityType
    {
        public LtbTcdoDmedicalFacilityType()
        {
            InverseTcdoDmedicalFacilityTypeParent = new HashSet<LtbTcdoDmedicalFacilityType>();
        }

        /// <summary>
        /// Unique generated number for the record used for row identity.
        /// </summary>
        public int TcdoDmedicalFacilityTypeId { get; set; }
        /// <summary>
        /// A code value for the current record.
        /// </summary>
        public string TcdoDmedicalFacilityTypeCode { get; set; }
        /// <summary>
        /// A brief representation or account of the current value represented by the associated record.
        /// </summary>
        public string ShortDescription { get; set; }
        /// <summary>
        /// A detailed representation of the current value represented by the associated record.
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// Record Parent ID with Foreign key to the Primary key of the table.
        /// </summary>
        public int? TcdoDmedicalFacilityTypeParentId { get; set; }
        /// <summary>
        /// The definition of the code value according to Regulatory Guidance or Business.
        /// </summary>
        public string ValueDefinition { get; set; }
        public string Guidance { get; set; }
        public DateTime? EstablishDate { get; set; }
        public DateTime StartCollecting { get; set; }
        /// <summary>
        /// Date the code was taken out of circulation for collection.  Incidents assigned the code value must have a Date Occurred less than or equal to the End Collecting Date.  The time for end collecting date should always be 2359.
        /// </summary>
        public DateTime? EndCollecting { get; set; }
        public string Used { get; set; }
        /// <summary>
        /// Numeric sorting order to control the way the codes/types are listed in drop downs within the application or module.
        /// </summary>
        public int? DisplayOrder { get; set; }
        /// <summary>
        /// The user who created the record.
        /// </summary>
        public string CreatedByUser { get; set; }
        /// <summary>
        /// The date the record was created.
        /// </summary>
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// Application used to create the record.
        /// </summary>
        public string CreatedByApp { get; set; }
        /// <summary>
        /// The user to last update the record.
        /// </summary>
        public string LastModifiedByUser { get; set; }
        /// <summary>
        /// The date the record was last updated.
        /// </summary>
        public DateTime LastModifiedDate { get; set; }
        /// <summary>
        /// Application used to last update the record.
        /// </summary>
        public string LastModifiedByApp { get; set; }

        public virtual LtbTcdoDmedicalFacilityType TcdoDmedicalFacilityTypeParent { get; set; }
        public virtual ICollection<LtbTcdoDmedicalFacilityType> InverseTcdoDmedicalFacilityTypeParent { get; set; }
    }
}