// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace store.dal.Models
{
    /// <summary>
    /// This table provides a listing of Unit Identification Codes (UICs) from DRRS/Asorts with start and end dates.  External Data Source.
    /// </summary>
    public partial class LtbUic
    {
        public LtbUic()
        {
            InverseUicparent = new HashSet<LtbUic>();
            LtbAircrafts = new HashSet<LtbAircraft>();
            LtbDoDdmismedicalTreatmentFacilities = new HashSet<LtbDoDdmismedicalTreatmentFacility>();
            LtbSubUics = new HashSet<LtbSubUic>();
            LtbUicadministrativeParentParentUics = new HashSet<LtbUicadministrativeParent>();
            LtbUicadministrativeParentUics = new HashSet<LtbUicadministrativeParent>();
            LtbUicdetailMajorArmyCommandUics = new HashSet<LtbUicdetail>();
            LtbUicdetailUics = new HashSet<LtbUicdetail>();
            LtbUichierarchyChildren = new HashSet<LtbUichierarchy>();
            LtbUichierarchyParents = new HashSet<LtbUichierarchy>();
            LtbUicoperationalParentParentUics = new HashSet<LtbUicoperationalParent>();
            LtbUicoperationalParentUics = new HashSet<LtbUicoperationalParent>();
        }

        /// <summary>
        /// Unique generated number for the record used for row identity.
        /// </summary>
        public int Uicid { get; set; }
        /// <summary>
        /// A code value for the current record.
        /// </summary>
        public string UnitIdentificationCode { get; set; }
        /// <summary>
        /// An indicator that the UIC record has been manually changed as opposed to update from data source.
        /// </summary>
        public bool ManuallyChanged { get; set; }
        /// <summary>
        /// Date the UIC record was manually updated.
        /// </summary>
        public DateTime? DateManuallyChanged { get; set; }
        /// <summary>
        /// Unique ID representing the OSHA Establishment.
        /// </summary>
        public int? OshaEstablishmentId { get; set; }
        /// <summary>
        /// Record Parent ID with Foreign key to the Primary key of the table.
        /// </summary>
        public int? UicparentId { get; set; }
        /// <summary>
        /// The definition of the code value according to Regulatory Guidance or Business.
        /// </summary>
        public string ValueDefinition { get; set; }
        /// <summary>
        /// The Business Rule, Regulatory or Other Army/DoD Guidance that states the code use requirement.  If available, include the publish and effective dates.
        /// </summary>
        public string Guidance { get; set; }
        /// <summary>
        /// The date the code value was established for use.  This date may or may not be the same as the start collecting date.
        /// </summary>
        public DateTime? EstablishDate { get; set; }
        /// <summary>
        /// Date the code value was available to be assigned to a record.  Records assigned the code value must have a Date greater than or equal to the Start Collecting Date. Will default to the current date upon entry unless otherwise specified.  The time for start collecting date should always be 0000.
        /// </summary>
        public DateTime StartCollecting { get; set; }
        /// <summary>
        /// Date the code was taken out of circulation for collection.  Incidents assigned the code value must have a Date Occurred less than or equal to the End Collecting Date.  The time for end collecting date should always be 2359.
        /// </summary>
        public DateTime? EndCollecting { get; set; }
        /// <summary>
        /// A flag to indicate whether the code is active and assigned to action records. If no records have the code assigned and it is no longer active,  then the current value should be N. Valid values: Y/N
        /// </summary>
        public string Used { get; set; }
        /// <summary>
        /// Numeric sorting order to control the way the codes/types are listed in drop downs within the application or module.
        /// </summary>
        public int? DisplayOrder { get; set; }
        /// <summary>
        /// The user who created the record.
        /// </summary>
        public string CreatedByUser { get; set; }
        /// <summary>
        /// The date the record was created.
        /// </summary>
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// Application used to create the record.
        /// </summary>
        public string CreatedByApp { get; set; }
        /// <summary>
        /// The user to last update the record.
        /// </summary>
        public string LastModifiedByUser { get; set; }
        /// <summary>
        /// The date the record was last updated.
        /// </summary>
        public DateTime LastModifiedDate { get; set; }
        /// <summary>
        /// Application used to last update the record.
        /// </summary>
        public string LastModifiedByApp { get; set; }

        public virtual LtbOshaEstablishment OshaEstablishment { get; set; }
        public virtual LtbUic Uicparent { get; set; }
        public virtual ICollection<LtbUic> InverseUicparent { get; set; }
        public virtual ICollection<LtbAircraft> LtbAircrafts { get; set; }
        public virtual ICollection<LtbDoDdmismedicalTreatmentFacility> LtbDoDdmismedicalTreatmentFacilities { get; set; }
        public virtual ICollection<LtbSubUic> LtbSubUics { get; set; }
        public virtual ICollection<LtbUicadministrativeParent> LtbUicadministrativeParentParentUics { get; set; }
        public virtual ICollection<LtbUicadministrativeParent> LtbUicadministrativeParentUics { get; set; }
        public virtual ICollection<LtbUicdetail> LtbUicdetailMajorArmyCommandUics { get; set; }
        public virtual ICollection<LtbUicdetail> LtbUicdetailUics { get; set; }
        public virtual ICollection<LtbUichierarchy> LtbUichierarchyChildren { get; set; }
        public virtual ICollection<LtbUichierarchy> LtbUichierarchyParents { get; set; }
        public virtual ICollection<LtbUicoperationalParent> LtbUicoperationalParentParentUics { get; set; }
        public virtual ICollection<LtbUicoperationalParent> LtbUicoperationalParentUics { get; set; }
    }
}