// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace store.dal.Models
{
    /// <summary>
    /// This table provides a listing of Unit Identification Codes (UICs) from DRRS/Asorts with start and end dates.  External Data Source.
    /// </summary>
    public partial class LtbUichierarchy
    {
        /// <summary>
        /// Unique generated number for the record used for row identity.
        /// </summary>
        public int UichierarchyId { get; set; }
        /// <summary>
        /// Unique ID for the UIC Parent.
        /// </summary>
        public int? ParentId { get; set; }
        /// <summary>
        /// Unique ID for the UIC Child.
        /// </summary>
        public int? ChildId { get; set; }
        /// <summary>
        /// Hierarchy Level of the Child UIC in relation to the Parent.
        /// </summary>
        public int? Level { get; set; }
        /// <summary>
        /// Date the code value was available to be assigned to a record.  Records assigned the code value must have a Date greater than or equal to the Start Collecting Date. Will default to the current date upon entry unless otherwise specified.  The time for start collecting date should always be 0000.
        /// </summary>
        public DateTime StartCollecting { get; set; }
        /// <summary>
        /// Date the code was taken out of circulation for collection.  Incidents assigned the code value must have a Date Occurred less than or equal to the End Collecting Date.  The time for end collecting date should always be 2359.
        /// </summary>
        public DateTime? EndCollecting { get; set; }
        /// <summary>
        /// A flag to indicate whether the code is active and assigned to action records. If no records have the code assigned and it is no longer active,  then the current value should be N. Valid values: Y/N
        /// </summary>
        public string Used { get; set; }
        /// <summary>
        /// The user who created the record.
        /// </summary>
        public string CreatedByUser { get; set; }
        /// <summary>
        /// The date the record was created.
        /// </summary>
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// Application used to create the record.
        /// </summary>
        public string CreatedByApp { get; set; }
        /// <summary>
        /// The user to last update the record.
        /// </summary>
        public string LastModifiedByUser { get; set; }
        /// <summary>
        /// The date the record was last updated.
        /// </summary>
        public DateTime LastModifiedDate { get; set; }
        /// <summary>
        /// Application used to last update the record.
        /// </summary>
        public string LastModifiedByApp { get; set; }

        public virtual LtbUic Child { get; set; }
        public virtual LtbUic Parent { get; set; }
    }
}