// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace store.dal.Models
{
    public partial class LtbUicdetail08132020
    {
        public int UicdetailId { get; set; }
        public string UnitIdentificationCode { get; set; }
        public string ShortName { get; set; }
        public string LongName { get; set; }
        public int Uicid { get; set; }
        public int? MajorArmyCommandUicid { get; set; }
        public string Uicabbreviation { get; set; }
        public int? UicarmyCommandTypeId { get; set; }
        public int? UicactivityStatusId { get; set; }
        public int? UicfunctionalAreaId { get; set; }
        public int? UiccommandAssignmentId { get; set; }
        public int? UicunitDescriptorId { get; set; }
        public string UicunitDescriptorCode { get; set; }
        public int? UicunitTypeConstructionId { get; set; }
        public int? HomeGeographicLocationId { get; set; }
        public int? PresentGeographicLocationId { get; set; }
        public string UnitPresentLocationZipCode { get; set; }
        public int? MobilizedResponseId { get; set; }
        public string Tpsn5 { get; set; }
        public int? UicunitLevelId { get; set; }
        public int? DoDunifiedCombatantCommandId { get; set; }
        public int? DoDserviceId { get; set; }
        public int? DoDserviceComponentId { get; set; }
        public int? ArmyBranchId { get; set; }
        public int? ArmyOrganizationTypeId { get; set; }
        public int? UicorganizationEntityStatusId { get; set; }
        public DateTime? OrganizationDate { get; set; }
        public int? OshaEstablishmentId { get; set; }
        public int? InstallationStationId { get; set; }
        public int? DrrsAsortsId { get; set; }
        public bool ManuallyChanged { get; set; }
        public DateTime? DateManuallyChanged { get; set; }
        public int? UicdetailParentId { get; set; }
        public string ValueDefinition { get; set; }
        public string Guidance { get; set; }
        public DateTime? EstablishDate { get; set; }
        public DateTime StartCollecting { get; set; }
        public DateTime? EndCollecting { get; set; }
        public string Used { get; set; }
        public int? DisplayOrder { get; set; }
        public string CreatedByUser { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedByApp { get; set; }
        public string LastModifiedByUser { get; set; }
        public DateTime LastModifiedDate { get; set; }
        public string LastModifiedByApp { get; set; }
    }
}