// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace store.dal.Models
{
    /// <summary>
    /// This table contains Unit Identification Code (UIC) Operational Parent UIC records obtains from DRRS/Asorts. External Data Source.
    /// </summary>
    public partial class LtbUicoperationalParent
    {
        /// <summary>
        /// Unique generated number for the record used for row identity.
        /// </summary>
        public int UicoperationalParentId { get; set; }
        /// <summary>
        /// Unique ID representing the UIC.
        /// </summary>
        public int Uicid { get; set; }
        /// <summary>
        /// Unique UIC ID representing the Operational Parent UIC.
        /// </summary>
        public int? ParentUicid { get; set; }
        /// <summary>
        /// An indicator that the UIC record has been manually changed as opposed to update from data source.
        /// </summary>
        public bool ManuallyChanged { get; set; }
        /// <summary>
        /// Date the UIC record was manually updated.
        /// </summary>
        public DateTime? DateManuallyChanged { get; set; }
        /// <summary>
        /// Date the code value was available to be assigned to a record.  Records assigned the code value must have a Date greater than or equal to the Start Collecting Date. Will default to the current date upon entry unless otherwise specified.  The time for start collecting date should always be 0000.
        /// </summary>
        public DateTime StartCollecting { get; set; }
        /// <summary>
        /// Date the code was taken out of circulation for collection.  Incidents assigned the code value must have a Date Occurred less than or equal to the End Collecting Date.  The time for end collecting date should always be 2359.
        /// </summary>
        public DateTime? EndCollecting { get; set; }
        /// <summary>
        /// A flag to indicate whether the code is active and assigned to action records. If no records have the code assigned and it is no longer active,  then the current value should be N. Valid values: Y/N
        /// </summary>
        public string Used { get; set; }
        /// <summary>
        /// The user who created the record.
        /// </summary>
        public string CreatedByUser { get; set; }
        /// <summary>
        /// The date the record was created.
        /// </summary>
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// Application used to create the record.
        /// </summary>
        public string CreatedByApp { get; set; }
        /// <summary>
        /// The user to last update the record.
        /// </summary>
        public string LastModifiedByUser { get; set; }
        /// <summary>
        /// The date the record was last updated.
        /// </summary>
        public DateTime LastModifiedDate { get; set; }
        /// <summary>
        /// Application used to last update the record.
        /// </summary>
        public string LastModifiedByApp { get; set; }

        public virtual LtbUic ParentUic { get; set; }
        public virtual LtbUic Uic { get; set; }
    }
}