// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace store.dal.Models
{
    public partial class LtbUic08182020updatePart2
    {
        public string Unitidentificationcode { get; set; }
        public int Uicid1 { get; set; }
        public DateTime? Establishdate { get; set; }
        public DateTime Startcollecting1 { get; set; }
        public DateTime? Endcollecting1 { get; set; }
        public string Used1 { get; set; }
        public int? Daydiff1 { get; set; }
        public int? Uicid2 { get; set; }
        public DateTime? StartCollecting2 { get; set; }
        public DateTime? EndCollecting2 { get; set; }
        public string Used2 { get; set; }
        public int? Daydiff2 { get; set; }
        public int? Uicid3 { get; set; }
        public DateTime? StartCollecting3 { get; set; }
        public DateTime? EndCollecting3 { get; set; }
        public string Used3 { get; set; }
        public int? Daydiff3 { get; set; }
        public int? Uicid4 { get; set; }
        public DateTime? StartCollecting4 { get; set; }
        public DateTime? EndCollecting4 { get; set; }
        public string Used4 { get; set; }
        public int? Daydiff4 { get; set; }
        public int? Uicid5 { get; set; }
        public DateTime? StartCollecting5 { get; set; }
        public DateTime? EndCollecting5 { get; set; }
        public string Used5 { get; set; }
        public string DeleteUicid1 { get; set; }
        public string DeleteUicid2 { get; set; }
        public string DeleteUicid3 { get; set; }
        public string DeleteUicid4 { get; set; }
        public string DeleteUicid5 { get; set; }
        public DateTime? NewEndCollecting { get; set; }
        public DateTime? NewStartCollecting { get; set; }
        public string CloseUic { get; set; }
    }
}