// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace store.dal.Models
{
    public partial class StbUicdetailDuplicateStationCleanUp7296
    {
        public string StationValid { get; set; }
        public string NewUsedValue { get; set; }
        public long? DuplicateRowIdentifier { get; set; }
        public int UicdetailId { get; set; }
        public string UnitIdentificationCode { get; set; }
        public string LongName { get; set; }
        public int Uicid { get; set; }
        public int? InstallationStationId { get; set; }
        public DateTime StartCollecting { get; set; }
        public DateTime? EndCollecting { get; set; }
        public int? DrrsAsortsId { get; set; }
        public string Used { get; set; }
    }
}